### ISSUE TITLE
Extend the FAQs on docs and website

### ISSUE THREAD

**Issue by whadar** [Peer5/peer5-docs#13]
Now it's on https://www.peer5.com/faq we should move to docs
Nice reference https://docs.intercom.io/help-and-faqs

**Comment by mrbar42** [comment]
**Question:** Is it possible to stream video from one peer to other peers without using server.
**Answer:** no, In order to use peer5 a proper HLS stream is needed - we recommand using wowza, red5 etc... as server software

**Comment by shacharz** [comment]
Another reference: http://www.streamroot.io/faq

**Comment by mrbar42** [comment]
**Question:** why is my stream is not accepted/invalid
**Answers:** In order to use peer5 you will need either an HLS stream or an MPEG-DASH stream. unlike regular video files, these streams have a manifest file as their entry point.
HLS have a `.m3u8` manifest file.
DASH have a `.mpd` manifest file.
If you are trying to integrate peer5 with any of these `.mp4` `.flv` `.mp3` `.ogg` `.webm` `.jpg` etc...
it will not work since these are not valid streams.  

---

**Question:** how do i setup an HLS/DASH stream
**Answer:** You can either use a paid service to convert and host the files for you such as:  

- maxcdn
- level3
- etc...

of use self hosted media servers such as:

- wowza
- nimble
- nginx-rtmp-module
- etc...

**Comment by whadar** [comment]
We should add more 👍 
This is yet another related FAQ - https://www.peer5.com/download/faq

**Comment by whadar** [comment]
The intention was the we will have an in-depth faq

**Comment by whadar** [comment]
@mrbar42 Can you add here (not yet in the page) questions that are related to integration issues (like timeout in the tester, which btw links to the FAQ page)

**Comment by shacharz** [comment]
I revised the FAQ we currently have in the website: https://docs.google.com/document/d/1TNrIT-fwpp6yZUFyydzjw2MCNasN_C78UmVwaLMdZdo/edit#heading=h.s4bgcaswwoh7
We should at least sync between the website and the docs
